name: Calculator CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest pylint

      - name: Build (placeholder)
        run: echo "Build step done (nothing to build for Python)"

      - name: Run Tests
        run: make test

      - name: Run Lint
        run: make lint
